# Generated by Django 4.2.2 on 2023-08-21 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'verbose_name': 'UserType', 'verbose_name_plural': 'UserType'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usertype'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_type'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^(\\+201|01|00201)[0-2,5]{1}[0-9]{8}')]),
        ),
        migrations.AddField(
            model_name='usertype',
            name='mobile_2',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^(\\+201|01|00201)[0-2,5]{1}[0-9]{8}')]),
        ),
        migrations.AddField(
            model_name='usertype',
            name='slug',
            field=models.SlugField(default='dsa', unique=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
