# Generated by Django 4.2.2 on 2023-08-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('rivets', 'Rivets'), ('drink', 'Drink'), ('baits', 'Baits')], max_length=20),
        ),
    ]
