# Generated by Django 4.2.2 on 2023-08-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_product_profit_alter_product_purchasing_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
    ]
