# Generated by Django 4.2.2 on 2023-08-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_remove_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'The price must be between 0 and 9999.99.'}}, help_text='Maximum 9999.99', max_digits=7, verbose_name='last price'),
        ),
    ]
