# Generated by Django 4.2.2 on 2023-08-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_product_last_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
