# Generated by Django 4.2.2 on 2023-08-29 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0006_alter_product_options'),
        ('users', '0002_alter_usertype_options_remove_address_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('qty', models.CharField(default=1, max_length=50)),
                ('price', models.CharField(default=0, max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_customer', to='users.usertype')),
                ('product', models.ManyToManyField(related_name='cart_product', to='medicine.product')),
            ],
        ),
    ]
